### ISSUE TITLE
SVG viewbox metadata

### ISSUE THREAD

**Issue by necolas** [w0rm/gulp-svgstore#15]
In order to use the output correctly for SVG's that have variable widths, you need to include the `viewBox` in the HTML:

```html
<svg viewBox="0 0 72 72" xmlns="http://www.w3.org/2000/svg">
  <use xlink:href="#icon-close"></use>
</svg>
```

What do you think about this plugin writing `icons.json` or similar, with `name: viewbox` pairs, so that downstream tools or a server can have access to the correct `viewBox` value for each icon.

**Comment by w0rm** [comment]
@necolas @Frizi  I added an example of how to extract viewboxes from combined svgs: https://github.com/w0rm/gulp-svgstore#extracting-metadata-from-combined-svg

This is now possible because gulp-svgstore caches cheerio in gulp file object.

If you need to extract from svg sources, then you may do the same with gulp-cheerio, pipe it to through2, collect data in `transform` function and write result json in `flush` function.

**Comment by necolas** [comment]
Cool. We wrote our own script to accommodate various requirements, but this will be useful for normal projects. Thanks!

**Comment by w0rm** [comment]
@necolas transformSvg wasn't a good idea in the first place, gulp-cheerio combination seems to be much better. It doesn't degrade performance, because cached `file.cheerio` is used instead of parsing file multiple times.
