### ISSUE TITLE
Pure JS API

### ISSUE THREAD

**Issue by shannonmoeller** [w0rm/gulp-svgstore#60]
I'd love this functionality as a pure JS api rather than being married to gulp. I haven't found a suitable alternative. Before forking this and building a new module myself I thought I'd ask if there were already plans for this or if there was a known alternative that isn't tied to another build tool (grunt, broccoli, cli, etc.).

Ideally something like this:

```js
var mergedSvgFile = svgstore(listOfSvgStringsOrBuffers, options);
```

**Comment by w0rm** [comment]
@shannonmoeller I have no plans about making this universal, because this is an opinionated library only for gulp ecosystem. The library is super simple, what matters more for this project is the method that uses `symbols` and how it may be used with other gulp plugins.

If you want to take a different approach, then you may look into https://github.com/jkphl/svg-sprite

**Comment by shannonmoeller** [comment]
That answers my question. Thanks!
